#! /bin/bash
if [[ -z "$1" || "$1" == "--help" ]]; then
	# Provide help to the user
	echo "usage: $0 <filename>"
	exit 1
fi


if [[ -f "$1" ]]; then
    echo "it's a file"
elif [[ -d "$1" ]]; then
     echo "it's a directory"
else
    echo "not found: $1"
fi
